[build]
builder = "nixpacks"
watchPatterns = ["server/**"]

[deploy]
startCommand = "cd server && node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
configFile = "server"
